In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("pdata.csv")

In [2]:
df.head()

Sensor1  Sensor2  Sensor3  Sensor4  Sensor5  Sensor6  Sensor7  Sensor8   
0        1        7        0       28       37       25       14        7  \
1        3        2       31        6       40       27        2        6   
2       13        8       32       24       14       43        7       13   
3        2        0       31       20       19        9       15        8   
4        7        4       10        6       24        2        1       14   

   Class  
0      1  
1      1  
2      1  
3      1  
4      1

In [3]:
df.tail()

Sensor1  Sensor2  Sensor3  Sensor4  Sensor5  Sensor6  Sensor7  Sensor8   
12496        0        1       17       91       40        4        1        1  \
12497        7       10       25       77       36        9        9        8   
12498        1        5       19        2       31        3        2        0   
12499        2        1        8       22       16        4        3        1   
12500        4        5        5       28        8        1        3        1   

       Class  
12496      5  
12497      5  
12498      5  
12499      5  
12500      5

In [4]:
df.shape

(12501, 9)

In [5]:
target=df['Class']

In [6]:
target.head()

0    1
1    1
2    1
3    1
4    1
Name: Class, dtype: int64

In [7]:
target.value_counts()

Class
4    2501
1    2500
2    2500
3    2500
5    2500
Name: count, dtype: int64

In [8]:
features=df[['Sensor1','Sensor2','Sensor3','Sensor4','Sensor5','Sensor6','Sensor7','Sensor8']]

In [9]:
features.head()

Sensor1  Sensor2  Sensor3  Sensor4  Sensor5  Sensor6  Sensor7  Sensor8
0        1        7        0       28       37       25       14        7
1        3        2       31        6       40       27        2        6
2       13        8       32       24       14       43        7       13
3        2        0       31       20       19        9       15        8
4        7        4       10        6       24        2        1       14

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.2, random_state = 0)

In [11]:
X_train.shape

(10000, 8)

In [12]:
X_test.shape

(2501, 8)

In [13]:
y_test.value_counts()

Class
4    519
3    502
2    497
1    495
5    488
Name: count, dtype: int64

# Logistic Regression

In [14]:
# Importing the LogisticRegression class from the linear_model module in sklearn
from sklearn.linear_model import LogisticRegression
# create object of the above classifier
clfy = LogisticRegression(random_state = 0) # pass seed to ensure results are reproducible
clfy.fit(X_train, y_train) # calls fit method from the classifier object to fit the data to our model

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [15]:
# Importing the confusion_matrix and accuracy_score class from the metrics module in sklearn
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = clfy.predict(X_test) # calls a predict method from the classfier object to target variable of the X_test
# creating a confussion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
# model score
accuracy_score(y_test, y_pred)

[[401  34  11  46   3]
 [ 24 397  33  38   5]
 [  7  28 329  87  51]
 [ 20  20 111 341  27]
 [  2   6  91  20 369]]


0.7345061975209916

In [16]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred, average='weighted')

(0.7435815960590094, 0.7345061975209916, 0.7379332765261438, None)

## Decision Tree

In [17]:
#Import Random Forest Model
from sklearn.tree import DecisionTreeClassifier

#Create a Gaussian Classifier
clf=DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)
y_pred

array([2, 4, 3, ..., 3, 1, 4])

In [18]:
# Importing the confusion_matrix and accuracy_score class from the metrics module in sklearn
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = clf.predict(X_test) # calls a predict method from the classfier object to target variable of the X_test
# creating a confussion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
# model score
accuracy_score(y_test, y_pred)

[[325  50  19  99   2]
 [ 20 329  69  79   0]
 [ 20  29 366  62  25]
 [ 15   4 206 277  17]
 [ 16  10 174  42 246]]


0.616953218712515

In [19]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred, average='weighted')

(0.6737949755380426, 0.616953218712515, 0.6266842234110463, None)

In [20]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=1000)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [21]:
# Importing the confusion_matrix and accuracy_score class from the metrics module in sklearn
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = clf.predict(X_test) # calls a predict method from the classfier object to target variable of the X_test
# creating a confussion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
# model score
accuracy_score(y_test, y_pred)

[[422  28   2  40   3]
 [ 22 410  26  38   1]
 [  7  23 344  71  57]
 [ 23  17  68 394  17]
 [  2   4  81  25 376]]


0.7780887644942023

In [22]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred, average='weighted')

(0.7825781375598336, 0.7780887644942023, 0.779672391341697, None)

In [23]:
def input1():
    clf.predict([[3,2,31,6,40,27,2,6]])

In [24]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd

# create a GaussianNB Naive Bayes classifier
clf = GaussianNB()

# train the classifier on the training data
clf.fit(X_train, y_train)

# make predictions on the testing data
y_pred = clf.predict(X_test)

# calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7065173930427829


In [25]:
from sklearn.metrics import precision_recall_fscore_support
x = precision_recall_fscore_support(y_test, y_pred, average='weighted')

In [26]:
clf.predict([[0,1,17,91,40,4,1,1]])

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([5])

In [27]:
ty = clf.predict([[1,7,0,28,37,25,14,7]])
ty

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([4])

In [28]:
type(ty)

numpy.ndarray

In [29]:
print(type(ty[0]))
print(ty[0])

<class 'numpy.int64'>
4


In [30]:
# Importing the confusion_matrix and accuracy_score class from the metrics module in sklearn
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = clf.predict(X_test) # calls a predict method from the classfier object to target variable of the X_test
# creating a confussion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
# model score

[[397  39  12  45   2]
 [ 27 377  64  21   8]
 [  7  13 391  37  54]
 [ 21  31 182 256  29]
 [  8   2 124   8 346]]


In [31]:
import gradio as gr

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay
import pandas as pd



def ml_visualizer(i1, i2, i3, i4, i5, i6, i7, i8, ml_model):
    
    if ml_model == "Logistic regression":
        # create object of the above classifier
        clf = LogisticRegression(random_state = 0,max_iter = 1000) # pass seed to ensure results are reproducible
        clf.fit(X_train, y_train) # calls fit method from the classifier object to fit the data to our model
        # Importing the confusion_matrix and accuracy_score class from the metrics module in sklearn
        y_pred = clf.predict(X_test) # calls a predict method from the classfier object to target variable of the X_test
        ty = clf.predict([[i1,i2,i3,i4,i5,i6,i7,i8]])
        
        
    elif ml_model == "Naive Bayes":
        # create a GaussianNB Naive Bayes classifier
        clf = GaussianNB()
        # train the classifier on the training data
        clf.fit(X_train, y_train)
        # make predictions on the testing data
        y_pred = clf.predict(X_test)
        # calculate the accuracy of the classifier
        accuracy = accuracy_score(y_test, y_pred)
        x = precision_recall_fscore_support(y_test, y_pred, average='weighted');
        ty = clf.predict([[i1,i2,i3,i4,i5,i6,i7,i8]])
        
        
    elif ml_model == "SVM":
        # create object of the above classifier
        clf = svm.SVC()
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test) # calls a predict method from the classfier object to target variable of the X_test
        # creating a confussion matrix
        cm = confusion_matrix(y_test, y_pred)
        # model score
        accuracy_score(y_test, y_pred)
        precision_recall_fscore_support(y_test, y_pred, average='weighted')
        ty = clf.predict([[i1,i2,i3,i4,i5,i6,i7,i8]])
        
        
    elif ml_model == "Random Forest":
        #Create a Gaussian Classifier
        clf=RandomForestClassifier(n_estimators=1000)

        #Train the model using the training sets y_pred=clf.predict(X_test)
        clf.fit(X_train,y_train)

        y_pred=clf.predict(X_test)

        y_pred = clf.predict(X_test) # calls a predict method from the classfier object to target variable of the X_test
        # creating a confussion matrix
        cm = confusion_matrix(y_test, y_pred)
        # model score
        accuracy_score(y_test, y_pred)
        precision_recall_fscore_support(y_test, y_pred, average='weighted')
        ty = clf.predict([[i1,i2,i3,i4,i5,i6,i7,i8]])
        
        
    elif ml_model == "Decision Tree":
        #Create a Gaussian Classifier
        clf=DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5)
        #Train the model using the training sets y_pred=clf.predict(X_test)
        clf.fit(X_train,y_train)
        y_pred=clf.predict(X_test)
        # model score
        accuracy_score(y_test, y_pred)
        precision_recall_fscore_support(y_test, y_pred, average='weighted')
        ty = clf.predict([[i1,i2,i3,i4,i5,i6,i7,i8]])
        
        
        
    can = 2+3
        
    if (ty[0]==1):
        out = "Fist"
    elif (ty[0]==2):
        out = "Flex_Left"
    elif (ty[0]==3):
        out = "Pinky"
    elif (ty[0]==4):
        out = "Rest"
    elif (ty[0]==5):
        out = "Flex_Right"

    return(out)
    

demo = gr.Interface(
    ml_visualizer,
    [
        gr.Slider(-200,200),
        gr.Slider(-200,200),
        gr.Slider(-200,200),
        gr.Slider(-200,200),
        gr.Slider(-200,200),
        gr.Slider(-200,200),
        gr.Slider(-200,200),
        gr.Slider(-200,200),
        gr.Radio(["Logistic regression", "Naive Bayes", "SVM", "Random Forest", "Decision Tree"])
#         gr.Dataframe(
#             headers=["Item", "Cost"],
#             datatype=["str", "number"],
#             label="Assets Purchased this Year",
#         ),
    ],
    outputs = ['text']
#     examples=[
#         [10000, "Married", [["Suit", 5000], ["Laptop", 800], ["Car", 1800]]],
#         [80000, "Single", [["Suit", 800], ["Watch", 1800], ["Car", 800]]],
#     ],
)

demo.launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature